# Generated by Django 6.0 on 2025-12-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
    ]
