# Generated by Django 6.0 on 2025-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_categorydb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Short_Description', models.TextField(blank=True, null=True)),
                ('detailed_Description', models.TextField(blank=True, null=True)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image1', models.ImageField(blank=True, null=True, upload_to='Product Image')),
                ('Product_Image2', models.ImageField(blank=True, null=True, upload_to='Product Image')),
                ('Product_Image3', models.ImageField(blank=True, null=True, upload_to='Product Image')),
            ],
        ),
    ]
