# Generated by Django 6.0 on 2025-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_RegistrationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirm_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
